2024-09-27 17:34:36,736 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'doc': '{"docstatus":0,"doctype":"Student","name":"new-student-ruslwdcexv","__islocal":1,"__unsaved":1,"owner":"Administrator","gender":"Female","status":"Active","grade":"A+","enrollment_date":"2024-09-27","subject":[{"docstatus":0,"doctype":"Subject","name":"new-subject-dwoucccbuk","__islocal":1,"__unsaved":1,"owner":"Administrator","parent":"new-student-ruslwdcexv","parentfield":"subject","parenttype":"Student","idx":1,"__unedited":false,"subject_name":"Maths","marks":null},{"docstatus":0,"doctype":"Subject","name":"new-subject-hahyguarcl","__islocal":1,"__unsaved":1,"owner":"Administrator","parent":"new-student-ruslwdcexv","parentfield":"subject","parenttype":"Student","idx":2,"__unedited":false,"subject_name":"Science","marks":null}],"student_id":9,"student_name":"AAAA"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2024-09-28 12:55:16,954 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'doc': '{"docstatus":0,"doctype":"Student","name":"new-student-vdqdfzxvtj","__islocal":1,"__unsaved":1,"owner":"Administrator","gender":"Female","status":"Active","grade":"A+","enrollment_date":"2024-09-28","subject":[{"docstatus":0,"doctype":"Subject","name":"new-subject-mrdalqrart","__islocal":1,"__unsaved":1,"owner":"Administrator","parent":"new-student-vdqdfzxvtj","parentfield":"subject","parenttype":"Student","idx":1,"__unedited":false,"subject_name":"phy"}],"student_id":13,"student_name":"G"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2024-10-03 08:56:52,851 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'doctype': 'RQ Job', 'fields': '["`tabRQ Job`.`name`","`tabRQ Job`.`owner`","`tabRQ Job`.`creation`","`tabRQ Job`.`modified`","`tabRQ Job`.`modified_by`","`tabRQ Job`.`_user_tags`","`tabRQ Job`.`_comments`","`tabRQ Job`.`_assign`","`tabRQ Job`.`_liked_by`","`tabRQ Job`.`docstatus`","`tabRQ Job`.`idx`","`tabRQ Job`.`queue`","`tabRQ Job`.`status`","`tabRQ Job`.`job_name`"]', 'filters': '[]', 'order_by': '`tabRQ Job`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1', 'cmd': 'frappe.desk.reportview.get'}
2024-10-03 09:09:33,056 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'doctype': 'RQ Job', 'current_filters': '[["RQ Job","status","=","failed"]]', 'field': 'assigned_to', 'cmd': 'frappe.desk.listview.get_group_by_count'}
2024-10-03 16:26:48,505 ERROR frappe Could not take error snapshot: name 'fixtures' is not defined
Site: frappe2.in
Form Dict: {'doctype': 'RQ Job', 'fields': '["`tabRQ Job`.`name`","`tabRQ Job`.`owner`","`tabRQ Job`.`creation`","`tabRQ Job`.`modified`","`tabRQ Job`.`modified_by`","`tabRQ Job`.`_user_tags`","`tabRQ Job`.`_comments`","`tabRQ Job`.`_assign`","`tabRQ Job`.`_liked_by`","`tabRQ Job`.`docstatus`","`tabRQ Job`.`idx`","`tabRQ Job`.`queue`","`tabRQ Job`.`status`","`tabRQ Job`.`job_name`"]', 'filters': '[]', 'order_by': '`tabRQ Job`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1641, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1610, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1476, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/library_management/library_management/hooks.py", line 257, in <module>
    fixtures
NameError: name 'fixtures' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1641, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1610, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1476, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/library_management/library_management/hooks.py", line 257, in <module>
    fixtures
NameError: name 'fixtures' is not defined
2024-10-03 16:26:48,519 ERROR frappe Failed to run after request hook
Site: frappe2.in
Form Dict: {'doctype': 'RQ Job', 'fields': '["`tabRQ Job`.`name`","`tabRQ Job`.`owner`","`tabRQ Job`.`creation`","`tabRQ Job`.`modified`","`tabRQ Job`.`modified_by`","`tabRQ Job`.`_user_tags`","`tabRQ Job`.`_comments`","`tabRQ Job`.`_assign`","`tabRQ Job`.`_liked_by`","`tabRQ Job`.`docstatus`","`tabRQ Job`.`idx`","`tabRQ Job`.`queue`","`tabRQ Job`.`status`","`tabRQ Job`.`job_name`"]', 'filters': '[]', 'order_by': '`tabRQ Job`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 146, in application
    run_after_request_hooks(request, response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 161, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1641, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1610, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1476, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/library_management/library_management/hooks.py", line 257, in <module>
    fixtures
NameError: name 'fixtures' is not defined
2024-10-03 18:28:29,634 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'author': 'B', 'cmd': 'library_management.library_management.doctype.library_member.library_member.get_author_articles'}
2024-10-03 18:28:29,772 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'author': 'B', 'cmd': 'library_management.library_management.doctype.library_member.library_member.get_author_articles'}
2024-10-03 18:29:08,952 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'author': 'B', 'cmd': 'library_management.library_management.doctype.library_member.library_member.get_author_articles'}
2024-10-03 18:51:56,786 ERROR frappe New Exception collected in error log
Site: frappe2.in
Form Dict: {'author': 'B', 'cmd': 'library_management.library_management.doctype.library_member.library_member.get_author_articles'}
